name: Build content indexes

on:
  push:
    paths:
      - "blog/**"
      - "projects/**"
      - "scripts/build_index.py"
  pull_request:
    paths:
      - "blog/**"
      - "projects/**"
      - "scripts/build_index.py"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: build-indexes-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build indexes
        run: |
          python scripts/build_index.py

      - name: Commit changes (if any)
        run: |
          set -e
          if git diff --quiet -- blog/index.json projects/index.json; then
            echo "No changes to index.json files."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blog/index.json projects/index.json
          git commit -m "chore(indexes): auto-build blog/projects indexes [skip ci]"
          git push
