name: Build & Publish static site to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Build Tailwind CSS
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps & build CSS (prod)
        run: |
          npm ci
          npm run build   # should output dist/assets/site.css

      # Build blog/projects indexes
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build blog/projects indexes
        run: |
          if [ -f scripts/build_index.py ]; then
            python scripts/build_index.py
          else
            echo "scripts/build_index.py not found; skipping index build"
          fi

      # Assemble dist
      - name: Prepare dist folder (only necessary files)
        run: |
          set -euo pipefail
          rm -rf dist_tmp
          mkdir -p dist_tmp/assets

          # index.html (root)
          cp -v index.html dist_tmp/

          # CSS is already built to dist/assets/site.css by npm run build
          # We'll move it from dist/assets to final dist_tmp/assets
          if [ -f dist/assets/site.css ]; then
            cp -v dist/assets/site.css dist_tmp/assets/site.css
          else
            echo "ERROR: dist/assets/site.css not found. Did Tailwind build run?" >&2
            exit 1
          fi

          # Optional shared assets (if you have them)
          if [ -d assets ]; then cp -rv assets/* dist_tmp/assets/ || true; fi
          if [ -d images ]; then mkdir -p dist_tmp/images && cp -rv images/* dist_tmp/images/ || true; fi

          # Blog
          if [ -d blog ]; then
            mkdir -p dist_tmp/blog
            rsync -a blog/ dist_tmp/blog/ \
              --exclude 'index.html' \
              --exclude '*.py' \
              --exclude 'scripts/' \
              --exclude 'README*' \
              --exclude '.DS_Store'
            [ -f dist_tmp/blog/index.json ] || echo "[]" > dist_tmp/blog/index.json
          fi

          # Projects
          if [ -d projects ]; then
            mkdir -p dist_tmp/projects
            rsync -a projects/ dist_tmp/projects/ \
              --exclude 'index.html' \
              --exclude '*.py' \
              --exclude 'scripts/' \
              --exclude 'README*' \
              --exclude '.DS_Store'
            [ -f dist_tmp/projects/index.json ] || echo "[]" > dist_tmp/projects/index.json
          fi

          touch dist_tmp/.nojekyll

          # Final sweep
          find dist_tmp -name '*.py' -delete || true
          rm -rf dist_tmp/scripts || true
          rm -f dist_tmp/README dist_tmp/README.md || true

          # Replace dist with dist_tmp
          rm -rf dist
          mv dist_tmp dist

      # Publish to gh-pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          force_orphan: true
          enable_jekyll: false
