name: Build & Publish static site to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # needed for pushing to gh-pages

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps & build CSS
        run: |
          npm ci
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Build the JSON indexes (but we won't publish the script itself)
      - name: Build blog/projects indexes
        run: |
          if [ -f scripts/build_index.py ]; then
            python scripts/build_index.py
          else
            echo "scripts/build_index.py not found; skipping index build"
          fi

          - name: Prepare dist folder (only necessary files)
          run: |
            set -e
            rm -rf dist
            mkdir -p dist/assets
            # index.html (root)
            cp -v index.html dist/
            # CSS already built to dist/assets/site.css by npm run build
            # Optional static assets
            if [ -d assets ]; then cp -rv assets/* dist/assets/; fi
            if [ -d images ]; then cp -rv images dist/images; fi
  
            # Blog
            if [ -d blog ]; then
              mkdir -p dist/blog
              rsync -a blog/ dist/blog/ \
                --exclude 'index.html' \
                --exclude '*.py' \
                --exclude 'scripts/' \
                --exclude 'README*' \
                --exclude '.DS_Store'
              [ -f dist/blog/index.json ] || echo "[]" > dist/blog/index.json
            fi
  
            # Projects
            if [ -d projects ]; then
              mkdir -p dist/projects
              rsync -a projects/ dist/projects/ \
                --exclude 'index.html' \
                --exclude '*.py' \
                --exclude 'scripts/' \
                --exclude 'README*' \
                --exclude '.DS_Store'
              [ -f dist/projects/index.json ] || echo "[]" > dist/projects/index.json
            fi
  
            touch dist/.nojekyll
            find dist -name '*.py' -delete || true
            rm -rf dist/scripts || true
            rm -f dist/README dist/README.md || true

      # Publish to gh-pages branch
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          force_orphan: true   # creates a clean gh-pages history (nice for pages)
          enable_jekyll: false # also creates .nojekyll

